const TRACKS = [
  {
    id: 1,
    title: "Photography",
    file: "9_1_Photography.mp3",
    sentences: [
      { start: 0.00, end: 2.20, text: "Over its two centuries of existence," },
      { start: 2.20, end: 8.00, text: "photography has undergone remarkable changes in how it's created, shared, and understood." },
      { start: 8.00, end: 12.80, text: "In 1839, Louis Daguerre introduced the daguerreotype process," },
      { start: 13.00, end: 16.20, text: "producing photographic images on silver-plated copper." },
      { start: 17.00, end: 20.00, text: "Though each image was unique and couldn't be reproduced," },
      { start: 20.00, end: 23.00, text: "daguerreotypes were prized for their clarity and realism." },
      { start: 24.00, end: 28.00, text: "They quickly gained popularity for portraits and scientific documentation." },
      { start: 28.00, end: 35.00, text: "As a result of Daguerre's invention, photography became not only a technical, but also an artistic endeavor." },
      { start: 36.00, end: 40.50, text: "By the early 20th century, photography had become more accessible." },
      { start: 40.50, end: 45.00, text: "allowing people to document everyday life through casual snapshots." },
      { start: 45.00, end: 53.00, text: "Innovations like Color Film and later, Digital photography transformed image making into an instant global activity." },
      { start: 53.00, end: 57.00, text: "It also brought previously less seen parts of the world into public view." },
      { start: 57.00, end: 65.00, text: "In the 1920s, for example, Ansel Adams used photography to capture the vast, unspoiled beauty of the American West." },
      { start: 65.00, end: 70.30, text: "Adams was originally trained as a musician and brought an artist's eye to his compositions." },
      { start: 70.30, end: 73.80, text: "Carefully considering light, form, and balance" },
      { start: 74.00, end: 81.50, text: "His black and white images of national parks emphasize dramatic light, sweeping landscapes, and intricate natural details." },
      { start: 81.50, end: 86.20, text: "These photographs didn't just showcase beauty; they stirred a deep emotional response" },
      { start: 86.40, end: 90.60, text: "and heightened public awareness about the need to protect fragile natural environments." },
      { start: 91.00, end: 98.00, text: "Despite rapid change, photography still relies on core principles: composition, lighting, and perspective." },
      { start: 98.00, end: 101.30, text: "These elements of photography are kind of like grammar and writing." },
      { start: 101.30, end: 107.00, text: "Just like grammar gives language its structure, so do composition, lighting, and perspective." },
      { start: 107.00, end: 112.00, text: "Umm well, they shape how a photograph tells a story and conveys emotions." },

    ],
    vocab: [
      { type: "word", en: "undergo", ko: "겪다, 경험하다" },
      { type: "word", en: "remarkable", ko: "놀라운, 주목할 만한" },
      { type: "word", en: "introduce", ko: "도입하다, 소개하다" },
      { type: "word", en: "unique", ko: "독특한, 유일한" },
      { type: "word", en: "reproduce", ko: "복제하다, 재현하다" },
      { type: "word", en: "prized", ko: "소중히 여겨지는, 귀중한" },
      { type: "word", en: "clarity", ko: "명료함, 선명함" },
      { type: "word", en: "accessible", ko: "접근 가능한, 이용하기 쉬운" },
      { type: "word", en: "document", ko: "기록하다" },
      { type: "word", en: "transform", ko: "변화시키다, 탈바꿈시키다" },
      { type: "word", en: "endeavor", ko: "노력, 시도" },
      { type: "word", en: "vast", ko: "광대한, 드넓은" },
      { type: "word", en: "unspoiled", ko: "훼손되지 않은, 자연 그대로의" },
      { type: "word", en: "composition", ko: "구도, 구성" },
      { type: "word", en: "emphasize", ko: "강조하다" },
      { type: "word", en: "intricate", ko: "복잡한, 정교한" },
      { type: "word", en: "stir", ko: "불러일으키다, 자극하다" },
      { type: "word", en: "perspective", ko: "관점, 원근법" },
      { type: "phrase", en: "not only A but also B", ko: "A뿐만 아니라 B도" },
      { type: "phrase", en: "as a result of", ko: "~의 결과로" },
      { type: "phrase", en: "be prized for", ko: "~로 높이 평가받다" },
      { type: "phrase", en: "transform A into B", ko: "A를 B로 바꾸다" },
      { type: "phrase", en: "bring A into view", ko: "A를 세상에 알리다" },
      { type: "phrase", en: "bring an artist's eye to", ko: "~에 예술가의 시각을 적용하다" },
      { type: "phrase", en: "rely on", ko: "~에 의존하다" },
      { type: "phrase", en: "stir an emotional response", ko: "감정적 반응을 불러일으키다" },
      { type: "phrase", en: "public awareness", ko: "대중의 인식" },
      { type: "phrase", en: "Just like A, so do B", ko: "마치 A인 것처럼, B도 그러하다" },
      { type: "phrase", en: "be kind of like", ko: "~와 비슷하다" },
      { type: "phrase", en: "give structure to", ko: "~에 구조를 부여하다" }
    ]
  }
,
  {
    id: 2,
    title: "Social Capital",
    file: "9_2_1_Social_Capital.mp3",
    sentences: [
      { start: 0.00, end: 3.50, text: "Social capital refers to the networks of relationships" },
      { start: 3.60, end: 7.30, text: "among people who live and work in a particular society." },
      { start: 7.30, end: 10.30, text: "Social capital can be bonding or bridging." },
      { start: 10.30, end: 14.34, text: "Bonding social capital occurs within a close-knit group," },
      { start: 14.40, end: 18.40, text: "such as family or close friends, where strong ties exist." },
      { start: 18.40, end: 25.80, text: "Bridging social capital refers to the connections that link people across different social groups," },
      { start: 25.90, end: 29.00, text: "which might involve acquaintances or colleagues." },
      { start: 29.00, end: 34.50, text: "High levels of social capital have been associated with numerous benefits," },
      { start: 34.50, end: 41.30, text: "including improved mental health, higher educational achievement, and greater economic prosperity." },
      { start: 41.30, end: 45.90, text: "It fosters trust, cooperation, and a sense of belonging." },
      { start: 46.00, end: 51.50, text: "However, it's important to note that social capital can also have negative aspects," },
      { start: 51.50, end: 58.00, text: "such as the potential for reinforcing social inequalities due to the exclusion of outsiders." },
      { start: 58.00, end: 63.70, text: "Understanding social capital helps sociologists analyze how communities function." },
      { start: 63.70, end: 67.40, text: "So let's now look at a case study of a specific community." },

    ],
    vocab: [
      { type: "word", en: "social capital", ko: "사회적 자본" },
      { type: "word", en: "bonding", ko: "유대, 결속" },
      { type: "word", en: "bridging", ko: "연결, 가교" },
      { type: "word", en: "close-knit", ko: "긴밀한, 단단히 결속된" },
      { type: "word", en: "ties", ko: "유대, 연결고리" },
      { type: "word", en: "acquaintance", ko: "지인, 아는 사람" },
      { type: "word", en: "colleague", ko: "동료" },
      { type: "word", en: "prosperity", ko: "번영, 번창" },
      { type: "word", en: "foster", ko: "촉진하다, 육성하다" },
      { type: "word", en: "cooperation", ko: "협력, 협동" },
      { type: "word", en: "belonging", ko: "소속감" },
      { type: "word", en: "reinforce", ko: "강화하다" },
      { type: "word", en: "inequality", ko: "불평등" },
      { type: "word", en: "exclusion", ko: "배제, 제외" },
      { type: "word", en: "outsider", ko: "외부인" },
      { type: "word", en: "sociologist", ko: "사회학자" },
      { type: "word", en: "analyze", ko: "분석하다" },
      { type: "word", en: "intentional", ko: "의도적인" },
      { type: "word", en: "identify", ko: "파악하다, 확인하다" },
      { type: "phrase", en: "refer to", ko: "~을 가리키다, 언급하다" },
      { type: "phrase", en: "occur within", ko: "~ 안에서 발생하다" },
      { type: "phrase", en: "strong ties", ko: "강한 유대" },
      { type: "phrase", en: "link people across", ko: "~을 넘어 사람들을 연결하다" },
      { type: "phrase", en: "be associated with", ko: "~와 관련되다" },
      { type: "phrase", en: "a sense of belonging", ko: "소속감" },
      { type: "phrase", en: "it's important to note that", ko: "~을 주목하는 것이 중요하다" },
      { type: "phrase", en: "due to", ko: "~ 때문에" },
      { type: "phrase", en: "case study", ko: "사례 연구" },
      { type: "phrase", en: "seek to", ko: "~하려고 하다" },
      { type: "phrase", en: "rather than", ko: "~ 대신에, ~보다는" },
      { type: "phrase", en: "result in", ko: "~을 초래하다, ~로 이어지다" },
      { type: "phrase", en: "be rejected by", ko: "~에 의해 거부되다" },
      { type: "phrase", en: "the established art community", ko: "기성 예술계" },
      { type: "phrase", en: "gain recognition", ko: "인정받다" },
      { type: "phrase", en: "pave the way for", ko: "~의 길을 열다" },
      { type: "phrase", en: "in terms of", ko: "~의 관점에서, ~면에서" },
      { type: "phrase", en: "be celebrated for", ko: "~로 칭송받다" }
    ]
  }
  ,
  {
    id: 3,
    title: "Impressionism",
    file: "9_2_1_Impressionism.mp3",
    sentences: [
      { start: 0.00, end: 5.21, text: "Impressionism is a painting style that began in France in the late 19th century." },
      { start: 5.21, end: 9.00, text: "It challenged traditional painting techniques and subject matter." },
      { start: 9.20, end: 16.80, text: "Artists like Claude Monet, Edgar Degas, and Pierre-Auguste Renoir sought to capture the fleeting effects of light and color." },
      { start: 17.00, end: 21.80, text: "Emphasizing the momentary impressions of a scene rather than its detailed realism." },
      { start: 22.00, end: 26.80, text: "They often painted outdoors to better observe and depict natural light." },
      { start: 27.00, end: 34.10, text: "This approach resulted in looser brush movement as they painted, compared to the precise techniques of earlier periods." },
      { start: 34.10, end: 40.80, text: "Initially, Impressionism faced harsh criticism and was rejected by the established art community." },
      { start: 41.00, end: 45.80, text: "However, it eventually gained recognition and profoundly influenced modern art." },
      { start: 46.00, end: 50.00, text: "Paving the way for movements like post-impressionism and modernism." },
      { start: 50.00, end: 54.70, text: "The emphasis on perception and experience, rather than meticulous detail," },
      { start: 55.00, end: 58.00, text: "encouraged artists to experiment with form and color." },
      { start: 58.00, end: 64.00, text: "Today, Impressionist works are celebrated for their innovative approach and emotional depth," },
      { start: 64.00, end: 67.30, text: "attracting millions of visitors to museums worldwide." },

    ],
    vocab: [
      { type: "word", en: "impressionism", ko: "인상주의" },
      { type: "word", en: "challenge", ko: "도전하다, 반박하다" },
      { type: "word", en: "technique", ko: "기법, 기술" },
      { type: "word", en: "subject matter", ko: "주제, 소재" },
      { type: "word", en: "fleeting", ko: "순간적인, 덧없는" },
      { type: "word", en: "impression", ko: "인상, 느낌" },
      { type: "word", en: "momentary", ko: "순간적인" },
      { type: "word", en: "depict", ko: "묘사하다, 그리다" },
      { type: "word", en: "loose", ko: "느슨한, 자유로운" },
      { type: "word", en: "precise", ko: "정밀한, 정확한" },
      { type: "word", en: "established", ko: "기성의, 확립된" },
      { type: "word", en: "harsh", ko: "가혹한, 혹독한" },
      { type: "word", en: "criticism", ko: "비판, 비평" },
      { type: "word", en: "recognition", ko: "인정, 명성" },
      { type: "word", en: "profoundly", ko: "깊이, 심오하게" },
      { type: "word", en: "modernism", ko: "모더니즘" },
      { type: "word", en: "perception", ko: "인식, 지각" },
      { type: "word", en: "meticulous", ko: "꼼꼼한, 세심한" },
      { type: "word", en: "encourage", ko: "장려하다, 격려하다" },
      { type: "word", en: "innovative", ko: "혁신적인" },
      { type: "word", en: "emotional depth", ko: "감정적 깊이" },
      { type: "phrase", en: "seek to", ko: "~하려고 하다" },
      { type: "phrase", en: "rather than", ko: "~ 대신에, ~보다는" },
      { type: "phrase", en: "result in", ko: "~을 초래하다, ~로 이어지다" },
      { type: "phrase", en: "compared to", ko: "~에 비해" },
      { type: "phrase", en: "be rejected by", ko: "~에 의해 거부되다" },
      { type: "phrase", en: "the established art community", ko: "기성 예술계" },
      { type: "phrase", en: "gain recognition", ko: "인정받다" },
      { type: "phrase", en: "pave the way for", ko: "~의 길을 열다" },
      { type: "phrase", en: "in terms of", ko: "~의 관점에서" },
      { type: "phrase", en: "be celebrated for", ko: "~로 칭송받다" },
      { type: "phrase", en: "experiment with", ko: "~을 가지고 실험하다" },
      { type: "phrase", en: "attracting millions of", ko: "수백만 명을 끌어들이며" },
      { type: "phrase", en: "museums worldwide", ko: "전 세계 박물관" }
    ]
  }
  // 새 음원 추가 시 여기에 추가:
  // {
  //   id: 2,
  //   title: "제목",
  //   file: "파일명.mp3",
  //   sentences: [
  //     { start: 0.00, end: 5.00, text: "문장 텍스트" },
  //     ...
  //   ]
  // }
];
