const TRACKS = [
  {
    id: 1,
    title: "Photography",
    file: "9_1_Photography.mp3",
    sentences: [
      { start: 0.00, end: 2.20, text: "Over its two centuries of existence," },
      { start: 2.20, end: 8.00, text: "photography has undergone remarkable changes in how it's created, shared, and understood." },
      { start: 8.00, end: 12.80, text: "In 1839, Louis Daguerre introduced the daguerreotype process," },
      { start: 13.00, end: 16.20, text: "producing photographic images on silver-plated copper." },
      { start: 17.00, end: 20.00, text: "Though each image was unique and couldn't be reproduced," },
      { start: 20.00, end: 23.00, text: "daguerreotypes were prized for their clarity and realism." },
      { start: 24.00, end: 28.00, text: "They quickly gained popularity for portraits and scientific documentation." },
      { start: 28.00, end: 35.00, text: "As a result of Daguerre's invention, photography became not only a technical, but also an artistic endeavor." },
      { start: 36.00, end: 40.50, text: "By the early 20th century, photography had become more accessible." },
      { start: 40.50, end: 45.00, text: "allowing people to document everyday life through casual snapshots." },
      { start: 45.00, end: 53.00, text: "Innovations like Color Film and later, Digital photography transformed image making into an instant global activity." },
      { start: 53.00, end: 57.00, text: "It also brought previously less seen parts of the world into public view." },
      { start: 57.00, end: 65.00, text: "In the 1920s, for example, Ansel Adams used photography to capture the vast, unspoiled beauty of the American West." },
      { start: 65.00, end: 70.30, text: "Adams was originally trained as a musician and brought an artist's eye to his compositions." },
      { start: 70.30, end: 73.80, text: "Carefully considering light, form, and balance" },
      { start: 74.00, end: 81.50, text: "His black and white images of national parks emphasize dramatic light, sweeping landscapes, and intricate natural details." },
      { start: 81.50, end: 86.20, text: "These photographs didn't just showcase beauty; they stirred a deep emotional response" },
      { start: 86.40, end: 90.60, text: "and heightened public awareness about the need to protect fragile natural environments." },
      { start: 91.00, end: 98.00, text: "Despite rapid change, photography still relies on core principles: composition, lighting, and perspective." },
      { start: 98.00, end: 101.30, text: "These elements of photography are kind of like grammar and writing." },
      { start: 101.30, end: 107.00, text: "Just like grammar gives language its structure, so do composition, lighting, and perspective." },
      { start: 107.00, end: 112.00, text: "Umm well, they shape how a photograph tells a story and conveys emotions." },

    ],
    vocab: [
      { type: "word", en: "undergo", ko: "겪다, 경험하다" },
      { type: "word", en: "remarkable", ko: "놀라운, 주목할 만한" },
      { type: "word", en: "introduce", ko: "도입하다, 소개하다" },
      { type: "word", en: "unique", ko: "독특한, 유일한" },
      { type: "word", en: "reproduce", ko: "복제하다, 재현하다" },
      { type: "word", en: "prized", ko: "소중히 여겨지는, 귀중한" },
      { type: "word", en: "clarity", ko: "명료함, 선명함" },
      { type: "word", en: "accessible", ko: "접근 가능한, 이용하기 쉬운" },
      { type: "word", en: "document", ko: "기록하다" },
      { type: "word", en: "transform", ko: "변화시키다, 탈바꿈시키다" },
      { type: "word", en: "endeavor", ko: "노력, 시도" },
      { type: "word", en: "vast", ko: "광대한, 드넓은" },
      { type: "word", en: "unspoiled", ko: "훼손되지 않은, 자연 그대로의" },
      { type: "word", en: "composition", ko: "구도, 구성" },
      { type: "word", en: "emphasize", ko: "강조하다" },
      { type: "word", en: "intricate", ko: "복잡한, 정교한" },
      { type: "word", en: "stir", ko: "불러일으키다, 자극하다" },
      { type: "word", en: "perspective", ko: "관점, 원근법" },
      { type: "phrase", en: "not only A but also B", ko: "A뿐만 아니라 B도" },
      { type: "phrase", en: "as a result of", ko: "~의 결과로" },
      { type: "phrase", en: "be prized for", ko: "~로 높이 평가받다" },
      { type: "phrase", en: "transform A into B", ko: "A를 B로 바꾸다" },
      { type: "phrase", en: "bring A into view", ko: "A를 세상에 알리다" },
      { type: "phrase", en: "bring an artist's eye to", ko: "~에 예술가의 시각을 적용하다" },
      { type: "phrase", en: "rely on", ko: "~에 의존하다" },
      { type: "phrase", en: "stir an emotional response", ko: "감정적 반응을 불러일으키다" },
      { type: "phrase", en: "public awareness", ko: "대중의 인식" },
      { type: "phrase", en: "Just like A, so do B", ko: "마치 A인 것처럼, B도 그러하다" },
      { type: "phrase", en: "be kind of like", ko: "~와 비슷하다" },
      { type: "phrase", en: "give structure to", ko: "~에 구조를 부여하다" }
    ]
  }
,
  {
    id: 2,
    title: "Social Capital",
    file: "9_2_1_Social_Capital.mp3",
    sentences: [
      { start: 0.00, end: 3.50, text: "Social capital refers to the networks of relationships" },
      { start: 3.60, end: 7.30, text: "among people who live and work in a particular society." },
      { start: 7.30, end: 10.30, text: "Social capital can be bonding or bridging." },
      { start: 10.30, end: 14.34, text: "Bonding social capital occurs within a close-knit group," },
      { start: 14.40, end: 18.40, text: "such as family or close friends, where strong ties exist." },
      { start: 18.40, end: 25.80, text: "Bridging social capital refers to the connections that link people across different social groups," },
      { start: 25.90, end: 29.00, text: "which might involve acquaintances or colleagues." },
      { start: 29.00, end: 34.50, text: "High levels of social capital have been associated with numerous benefits," },
      { start: 34.50, end: 41.30, text: "including improved mental health, higher educational achievement, and greater economic prosperity." },
      { start: 41.30, end: 45.90, text: "It fosters trust, cooperation, and a sense of belonging." },
      { start: 46.00, end: 51.50, text: "However, it's important to note that social capital can also have negative aspects," },
      { start: 51.50, end: 58.00, text: "such as the potential for reinforcing social inequalities due to the exclusion of outsiders." },
      { start: 58.00, end: 63.70, text: "Understanding social capital helps sociologists analyze how communities function." },
      { start: 63.70, end: 67.40, text: "So let's now look at a case study of a specific community." },

    ],
    vocab: [
      { type: "word", en: "social capital", ko: "사회적 자본" },
      { type: "word", en: "bonding", ko: "유대, 결속" },
      { type: "word", en: "bridging", ko: "연결, 가교" },
      { type: "word", en: "close-knit", ko: "긴밀한, 단단히 결속된" },
      { type: "word", en: "ties", ko: "유대, 연결고리" },
      { type: "word", en: "acquaintance", ko: "지인, 아는 사람" },
      { type: "word", en: "colleague", ko: "동료" },
      { type: "word", en: "prosperity", ko: "번영, 번창" },
      { type: "word", en: "foster", ko: "촉진하다, 육성하다" },
      { type: "word", en: "cooperation", ko: "협력, 협동" },
      { type: "word", en: "belonging", ko: "소속감" },
      { type: "word", en: "reinforce", ko: "강화하다" },
      { type: "word", en: "inequality", ko: "불평등" },
      { type: "word", en: "exclusion", ko: "배제, 제외" },
      { type: "word", en: "outsider", ko: "외부인" },
      { type: "word", en: "sociologist", ko: "사회학자" },
      { type: "word", en: "analyze", ko: "분석하다" },
      { type: "word", en: "intentional", ko: "의도적인" },
      { type: "word", en: "identify", ko: "파악하다, 확인하다" },
      { type: "phrase", en: "refer to", ko: "~을 가리키다, 언급하다" },
      { type: "phrase", en: "occur within", ko: "~ 안에서 발생하다" },
      { type: "phrase", en: "strong ties", ko: "강한 유대" },
      { type: "phrase", en: "link people across", ko: "~을 넘어 사람들을 연결하다" },
      { type: "phrase", en: "be associated with", ko: "~와 관련되다" },
      { type: "phrase", en: "a sense of belonging", ko: "소속감" },
      { type: "phrase", en: "it's important to note that", ko: "~을 주목하는 것이 중요하다" },
      { type: "phrase", en: "due to", ko: "~ 때문에" },
      { type: "phrase", en: "case study", ko: "사례 연구" },
      { type: "phrase", en: "seek to", ko: "~하려고 하다" },
      { type: "phrase", en: "rather than", ko: "~ 대신에, ~보다는" },
      { type: "phrase", en: "result in", ko: "~을 초래하다, ~로 이어지다" },
      { type: "phrase", en: "be rejected by", ko: "~에 의해 거부되다" },
      { type: "phrase", en: "the established art community", ko: "기성 예술계" },
      { type: "phrase", en: "gain recognition", ko: "인정받다" },
      { type: "phrase", en: "pave the way for", ko: "~의 길을 열다" },
      { type: "phrase", en: "in terms of", ko: "~의 관점에서, ~면에서" },
      { type: "phrase", en: "be celebrated for", ko: "~로 칭송받다" }
    ]
  }
  ,
  {
    id: 3,
    title: "Impressionism",
    file: "9_2_1_Impressionism.mp3",
    sentences: [
      { start: 0.00, end: 5.21, text: "Impressionism is a painting style that began in France in the late 19th century." },
      { start: 5.21, end: 9.00, text: "It challenged traditional painting techniques and subject matter." },
      { start: 9.20, end: 16.80, text: "Artists like Claude Monet, Edgar Degas, and Pierre-Auguste Renoir sought to capture the fleeting effects of light and color." },
      { start: 17.00, end: 21.80, text: "Emphasizing the momentary impressions of a scene rather than its detailed realism." },
      { start: 22.00, end: 26.80, text: "They often painted outdoors to better observe and depict natural light." },
      { start: 27.00, end: 34.10, text: "This approach resulted in looser brush movement as they painted, compared to the precise techniques of earlier periods." },
      { start: 34.10, end: 40.80, text: "Initially, Impressionism faced harsh criticism and was rejected by the established art community." },
      { start: 41.00, end: 45.80, text: "However, it eventually gained recognition and profoundly influenced modern art." },
      { start: 46.00, end: 50.00, text: "Paving the way for movements like post-impressionism and modernism." },
      { start: 50.00, end: 54.70, text: "The emphasis on perception and experience, rather than meticulous detail," },
      { start: 55.00, end: 58.00, text: "encouraged artists to experiment with form and color." },
      { start: 58.00, end: 64.00, text: "Today, Impressionist works are celebrated for their innovative approach and emotional depth," },
      { start: 64.00, end: 67.30, text: "attracting millions of visitors to museums worldwide." },

    ],
    vocab: [
      { type: "word", en: "impressionism", ko: "인상주의" },
      { type: "word", en: "challenge", ko: "도전하다, 반박하다" },
      { type: "word", en: "technique", ko: "기법, 기술" },
      { type: "word", en: "subject matter", ko: "주제, 소재" },
      { type: "word", en: "fleeting", ko: "순간적인, 덧없는" },
      { type: "word", en: "impression", ko: "인상, 느낌" },
      { type: "word", en: "momentary", ko: "순간적인" },
      { type: "word", en: "depict", ko: "묘사하다, 그리다" },
      { type: "word", en: "loose", ko: "느슨한, 자유로운" },
      { type: "word", en: "precise", ko: "정밀한, 정확한" },
      { type: "word", en: "established", ko: "기성의, 확립된" },
      { type: "word", en: "harsh", ko: "가혹한, 혹독한" },
      { type: "word", en: "criticism", ko: "비판, 비평" },
      { type: "word", en: "recognition", ko: "인정, 명성" },
      { type: "word", en: "profoundly", ko: "깊이, 심오하게" },
      { type: "word", en: "modernism", ko: "모더니즘" },
      { type: "word", en: "perception", ko: "인식, 지각" },
      { type: "word", en: "meticulous", ko: "꼼꼼한, 세심한" },
      { type: "word", en: "encourage", ko: "장려하다, 격려하다" },
      { type: "word", en: "innovative", ko: "혁신적인" },
      { type: "word", en: "emotional depth", ko: "감정적 깊이" },
      { type: "phrase", en: "seek to", ko: "~하려고 하다" },
      { type: "phrase", en: "rather than", ko: "~ 대신에, ~보다는" },
      { type: "phrase", en: "result in", ko: "~을 초래하다, ~로 이어지다" },
      { type: "phrase", en: "compared to", ko: "~에 비해" },
      { type: "phrase", en: "be rejected by", ko: "~에 의해 거부되다" },
      { type: "phrase", en: "the established art community", ko: "기성 예술계" },
      { type: "phrase", en: "gain recognition", ko: "인정받다" },
      { type: "phrase", en: "pave the way for", ko: "~의 길을 열다" },
      { type: "phrase", en: "in terms of", ko: "~의 관점에서" },
      { type: "phrase", en: "be celebrated for", ko: "~로 칭송받다" },
      { type: "phrase", en: "experiment with", ko: "~을 가지고 실험하다" },
      { type: "phrase", en: "attracting millions of", ko: "수백만 명을 끌어들이며" },
      { type: "phrase", en: "museums worldwide", ko: "전 세계 박물관" }
    ]
  }
,
  {
    id: 4,
    title: "LC 14 TPO 11 Distraction Display",
    file: "LC14_TPO11_Set1-2_DistractionDisplay.mp3",
    sentences: [
      { start: 11.50, end: 17.80, text: "Okay. Today, we're going to continue our discussion of the parenting behaviors of birds" },
      { start: 17.80, end: 23.40, text: "and we're going to start by talking about what are known as \"distraction displays.\"" },
      { start: 23.40, end: 29.50, text: "Now, if you're a bird and there is a predator around, what are you going to do?" },
      { start: 29.80, end: 35.30, text: "Well, for one thing, you are going to try to attract as little attention as possible, right?" },
      { start: 35.30, end: 39.60, text: "Because, if the predator doesn't know you're there, it's not going to try to eat you." },
      { start: 39.60, end: 44.70, text: "But, sometimes certain species of birds do the exact opposite," },
      { start: 44.70, end: 49.80, text: "when a predator approaches they do their best to attract the attention of that predator." },
      { start: 49.80, end: 52.10, text: "Now, why would they do that?" },
      { start: 52.10, end: 59.50, text: "Well, they do that to draw the predator away from their nests, away from their eggs or their young birds," },
      { start: 59.50, end: 67.00, text: "and the behaviors that the birds engage in to distract predators are called 'distraction displays.'" },
      { start: 67.00, end: 72.00, text: "And, there are a number of different kinds of distraction displays." },
      { start: 72.00, end: 76.70, text: "Most of the time, when birds are engaging in distraction displays," },
      { start: 76.80, end: 83.70, text: "they're going to be pretending either that they have an injury or that they're ill or that they're exhausted." },
      { start: 83.90, end: 88.80, text: "You know, something that'll make the predator think, \"Ah, here's an easy meal!\"" },
      { start: 88.80, end: 94.70, text: "One pretty common distraction display is what's called 'the broken wing display.'" },
      { start: 94.70, end: 102.10, text: "And, um, in a broken wing display the bird spreads and drags a wing or its tail" },
      { start: 102.10, end: 106.00, text: "and while it does that, it slowly moves away from the nest." },
      { start: 106.10, end: 113.60, text: "So, it really looks like a bird with a broken wing and these broken wing displays can be pretty convincing." },
      { start: 113.60, end: 124.70, text: "Another version of this kind of distraction display is where the bird creates the impression of a mouse or some other small animal that's running along the ground." },
      { start: 124.70, end: 131.20, text: "A good example of that kind of display is created by a bird called 'the Purple Sandpiper.'" },
      { start: 131.20, end: 139.20, text: "Now, what the Purple Sandpiper does is, when a predator approaches, it drags its wings," },
      { start: 139.20, end: 147.80, text: "uh, but not to give impression that its wing's broken, but to create the illusion that it has a second pair of legs" },
      { start: 147.80, end: 153.30, text: "and then it raises its feathers, so it looks like it's got a coat of fur," },
      { start: 153.30, end: 161.00, text: "and then it runs along the ground, swerving left and right, you know, like it's running around little rocks and sticks." },
      { start: 161.00, end: 173.00, text: "As it goes along, it makes this little squealing noise, so from a distance, it really looks and sounds like a little animal running along the ground, trying to get away." },
      { start: 173.00, end: 177.20, text: "Again, to the predator, it looks like an easy meal." },
      { start: 177.50, end: 184.50, text: "Now, what's interesting is that birds have different levels of performance of these distraction displays." },
      { start: 184.50, end: 190.20, text: "They don't give their top performance, their prime-time performance, every time." },
      { start: 190.20, end: 203.45, text: "What they do is they save their best performances, their most conspicuous and most risky displays, for the time just before the baby birds become able to take care of themselves." },
      { start: 203.45, end: 210.65, text: "And, they time it that way because that's when they'll have made the greatest investment in parenting their young." },
      { start: 210.65, end: 215.25, text: "So, they're not gonna put on their best performance just after they've laid their eggs," },
      { start: 215.30, end: 219.70, text: "because they haven't invested that much time or energy in parenting, yet." },
      { start: 219.70, end: 222.70, text: "The top performances are gonna come later." },
      { start: 222.70, end: 229.30, text: "Now, you have some birds that are quite mature, quite capable, almost as soon as they hatch" },
      { start: 229.40, end: 236.20, text: "and, in that case, the parent will put on the most conspicuous distraction displays just before the babies hatch," },
      { start: 236.20, end: 241.00, text: "because once the babies are hatched, they can pretty much take care of themselves." },
      { start: 241.00, end: 244.90, text: "And then, you have other birds that are helpless when they hatch." },
      { start: 244.90, end: 251.50, text: "In that case, the parent will save its best performances until just before the babies get their feathers" },

    ],
    vocab: [
      { type: "word", en: "predator", ko: "포식자" },
      { type: "word", en: "distraction display", ko: "유인 행동" },
      { type: "word", en: "species", ko: "종" },
      { type: "word", en: "injury", ko: "부상" },
      { type: "word", en: "exhausted", ko: "지친" },
      { type: "word", en: "convincing", ko: "설득력 있는" },
      { type: "word", en: "impression", ko: "인상" },
      { type: "word", en: "illusion", ko: "환상" },
      { type: "word", en: "swerving", ko: "방향을 바꾸며" },
      { type: "word", en: "squealing", ko: "끽끽거리는" },
      { type: "word", en: "conspicuous", ko: "눈에 띄는" },
      { type: "word", en: "investment", ko: "투자" },
      { type: "word", en: "mature", ko: "성숙한" },
      { type: "word", en: "hatch", ko: "부화하다" },
      { type: "word", en: "helpless", ko: "무력한" },
      { type: "word", en: "feathers", ko: "깃털" },
      { type: "word", en: "parenting", ko: "양육" },
      { type: "phrase", en: "engage in", ko: "~에 참여하다" },
      { type: "phrase", en: "draw A away from B", ko: "B로부터 A를 유인하다" },
      { type: "phrase", en: "do their best to", ko: "~하기 위해 최선을 다하다" },
      { type: "phrase", en: "give the impression of", ko: "~의 인상을 주다" },
      { type: "phrase", en: "create the illusion that", ko: "~라는 환상을 만들다" },
      { type: "phrase", en: "save A for B", ko: "B를 위해 A를 아끼다" },
      { type: "phrase", en: "be capable of", ko: "~할 수 있다" },
      { type: "phrase", en: "invest in", ko: "~에 투자하다" },
      { type: "phrase", en: "take care of themselves", ko: "스스로를 돌보다" },
      { type: "phrase", en: "put on a performance", ko: "연기를 하다" }
    ]
  }
  ,
  {
    id: 5,
    title: "LC 14 TPO 11 Cape Cod House",
    file: "LC14_TPO11_Set1-3_CapeCodHouse.mp3",
    sentences: [
      { start: 7.00, end: 10.10, text: "Today, we're taking a little detour" },
      { start: 10.10, end: 14.05, text: "from the grand styles of public architecture we've been studying" },
      { start: 14.05, end: 18.75, text: "to look at residential architecture in the United States." },
      { start: 18.75, end: 22.85, text: "Since this is something we can all identify with," },
      { start: 22.85, end: 33.00, text: "I think it'll help us see the relationship between the function of a structure and its, its style, or form." },
      { start: 33.00, end: 38.50, text: "This has been an ongoing theme in our discussions and we'll be getting back to it in just a moment," },
      { start: 38.50, end: 43.45, text: "but before we get started, I want you to take a moment to think." },
      { start: 43.45, end: 52.55, text: "Does anyone know what the single most popular style for a house in the United States is today? Bob?" },
      { start: 52.55, end: 54.85, text: "I bet it's the Ranch-style house." },
      { start: 54.85, end: 62.15, text: "Well, in this area, probably, but are we typical? Yeah, Sue?" },
      { start: 62.15, end: 68.45, text: "How about the kind of house my grandparents live in? They call it, uh, a Cape Cod." },
      { start: 68.45, end: 75.75, text: "That's the one. Here's a drawing of what we consider of a classic Cape Cod house." },
      { start: 77.00, end: 82.35, text: "These days you see this style all over the United States," },
      { start: 82.35, end: 90.30, text: "but it first showed up in the US Northeast, in the New England region, around the late 1600's." },
      { start: 90.30, end: 101.70, text: "For those of you who don't know the Northeast coastal region, Cape Cod is a peninsula, a narrow strip of land that juts out into the Atlantic." },
      { start: 113.40, end: 120.20, text: "Now, why did the Cape Cod style house become so popular in the Northeast?" },
      { start: 132.20, end: 139.40, text: "Well, one reason is that it's a great example of form following function." },
      { start: 139.40, end: 148.40, text: "We've talked about this design principle a lot, about form following function, and what did we say it meant?" },
      { start: 148.40, end: 151.45, text: "Someone give me an application of this principle." },
      { start: 151.45, end: 158.70, text: "What does this concept that form should follow function? How would it be applied to housing design?" },
      { start: 158.70, end: 165.10, text: "Well, if it means that the design of a building should be based on the needs of the people who use it," },
      { start: 165.10, end: 177.30, text: "then, well, the architect has to be very practical, to think about the people who'll actually be living in the house or working in the office building, whatever." },
      { start: 177.30, end: 184.20, text: "So, for the architect, it's all about the users, not about showing off how creative you can be." },
      { start: 184.20, end: 194.90, text: "Good. Of course, for a Cape Cod house, it might be even more accurate to say that form also follows climate." },
      { start: 194.90, end: 197.80, text: "Who knows what the climate's like on Cape Cod?" },
      { start: 197.80, end: 200.05, text: "Cold in the winter." },
      { start: 200.05, end: 204.30, text: "And, whenever I visit my grandparents, it's really wet." },
      { start: 204.30, end: 210.00, text: "It's usually either raining or snowing or foggy, and windy, too." },
      { start: 210.00, end: 213.70, text: "I guess because it's so exposed to the ocean?" },
      { start: 213.70, end: 224.15, text: "That's right. So, take another look at this drawing and you can imagine how this design might be particularly helpful in that kind of climate." },
      { start: 224.16, end: 229.10, text: "Notice how the house sits fairly low to the ground." },
      { start: 229.10, end: 237.15, text: "This relatively low, compact structure helps the house withstand the strong winds blowing off the ocean" },
      { start: 237.15, end: 245.40, text: "and look at the slope of the roof. The steep angle helps keep off all that rain and snow that accumulates in the winter." },
      { start: 245.40, end: 254.00, text: "Another thing, Cape Cod houses usually face south, to take advantage of the sun's warmth through the windows." },
      { start: 254.00, end: 255.85, text: "That's helpful in winter." },
      { start: 255.85, end: 261.60, text: "Now, what can you tell me about the chimney? About its location?" },
      { start: 261.60, end: 268.40, text: "Well, it's in the middle, because, does that have something to do with heating the houses?" },
      { start: 268.40, end: 271.85, text: "I mean since the heat never has to travel very far." },
      { start: 271.85, end: 275.00, text: "That'd mean you can heat the house more efficiently, right?" },
      { start: 275.00, end: 281.45, text: "Exactly. Now, see how the house has very little exterior decoration." },
      { start: 281.45, end: 284.95, text: "That's also typical of early Cape Cod houses." },
      { start: 284.95, end: 291.35, text: "The wind was one reason, nothing sticking out that might blow away in the harsh weather," },
      { start: 291.35, end: 302.10, text: "but there was probably another reason, not related to the climate. Umm, more, uh, more a reflection of rural New England society back then." },
      { start: 302.10, end: 309.70, text: "You see, Cape Cod houses were not built in the big cities, where all the rich people lived back then." },
      { start: 309.70, end: 318.40, text: "These were modest dwellings, the people who built them simply couldn't afford lots of expensive decorative details," },
      { start: 318.40, end: 322.00, text: "but it was more than just the matter of money." },
      { start: 322.00, end: 327.55, text: "In these rural areas, people depended on each other for survival." },
      { start: 327.55, end: 333.22, text: "Neighbors had to help and support each other in a difficult environment." },
      { start: 333.22, end: 337.45, text: "So, you didn't want to appear to be showing off." },
      { start: 337.45, end: 346.15, text: "You'd want to avoid anything that might set you apart from your neighbors, the same people you might need to help you someday." },
      { start: 346.15, end: 352.00, text: "So, so, all this helped to create an attitude of conformity in the community" },
      { start: 352.00, end: 361.10, text: "and you can see why a modest, a very plain style, would've become so widely imitated throughout rural New England." },
      { start: 361.10, end: 364.50, text: "It is plain, but, you know, it's nice-looking." },
      { start: 364.50, end: 376.00, text: "Good point! And, in fact, it's precisely that aesthetic appeal, the purity, the nearly perfect proportions of the house," },
      { start: 376.00, end: 380.30, text: "that's another reason for the Cape Cod's enduring popularity," },
      { start: 380.30, end: 387.00, text: "even in places where the climate is so mild that its functional design doesn't matter." }
    ],
    vocab: [
      { type: "word", en: "detour", ko: "우회, 돌아가기" },
      { type: "word", en: "residential", ko: "주거의, 주택의" },
      { type: "word", en: "ongoing", ko: "지속적인, 진행 중인" },
      { type: "word", en: "peninsula", ko: "반도" },
      { type: "word", en: "jut out", ko: "돌출되다, 튀어나오다" },
      { type: "word", en: "compact", ko: "소형의, 압축된" },
      { type: "word", en: "withstand", ko: "견디다, 버티다" },
      { type: "word", en: "accumulate", ko: "쌓이다, 축적되다" },
      { type: "word", en: "chimney", ko: "굴뚝" },
      { type: "word", en: "efficiently", ko: "효율적으로" },
      { type: "word", en: "exterior", ko: "외부의, 외관" },
      { type: "word", en: "harsh", ko: "혹독한, 거친" },
      { type: "word", en: "modest", ko: "소박한, 검소한" },
      { type: "word", en: "dwelling", ko: "주거지, 거택" },
      { type: "word", en: "decorative", ko: "장식적인" },
      { type: "word", en: "conformity", ko: "순응, 동조" },
      { type: "word", en: "imitate", ko: "모방하다, 따라하다" },
      { type: "word", en: "aesthetic", ko: "미적인, 심미적인" },
      { type: "word", en: "proportion", ko: "비율, 균형" },
      { type: "word", en: "enduring", ko: "지속적인, 오래가는" },
      { type: "phrase", en: "take a detour", ko: "우회하다, 잠시 다른 주제로 넘어가다" },
      { type: "phrase", en: "identify with", ko: "~에 공감하다" },
      { type: "phrase", en: "form follows function", ko: "형태는 기능을 따른다" },
      { type: "phrase", en: "take advantage of", ko: "~을 활용하다" },
      { type: "phrase", en: "stick out", ko: "튀어나오다, 눈에 띄다" },
      { type: "phrase", en: "set apart from", ko: "~와 구별되다" },
      { type: "phrase", en: "couldn't afford", ko: "~할 여유가 없다" },
      { type: "phrase", en: "depend on each other", ko: "서로 의존하다" },
      { type: "phrase", en: "show off", ko: "과시하다" },
      { type: "phrase", en: "be applied to", ko: "~에 적용되다" },
      { type: "phrase", en: "in just a moment", ko: "잠시 후에" },
      { type: "phrase", en: "precisely that", ko: "바로 그것" }
    ]
  }
  // 새 음원 추가 시 여기에 추가:
  // {
  //   id: 2,
  //   title: "제목",
  //   file: "파일명.mp3",
  //   sentences: [
  //     { start: 0.00, end: 5.00, text: "문장 텍스트" },
  //     ...
  //   ]
  // }
];
