const TRACKS = [
  {
    id: 1,
    title: "Photography",
    file: "9_1_Photography.m4a",
    sentences: [
      { start: 0.00, end: 2.20, text: "Over its two centuries of existence," },
      { start: 2.20, end: 8.00, text: "photography has undergone remarkable changes in how it's created, shared, and understood." },
      { start: 8.00, end: 12.80, text: "In 1839, Louis Daguerre introduced the daguerreotype process," },
      { start: 13.00, end: 16.20, text: "producing photographic images on silver-plated copper." },
      { start: 17.00, end: 20.00, text: "Though each image was unique and couldn't be reproduced," },
      { start: 20.00, end: 23.00, text: "daguerreotypes were prized for their clarity and realism." },
      { start: 24.00, end: 28.00, text: "They quickly gained popularity for portraits and scientific documentation." },
      { start: 28.00, end: 35.00, text: "As a result of Daguerre's invention, photography became not only a technical, but also an artistic endeavor." },
      { start: 36.00, end: 40.50, text: "By the early 20th century, photography had become more accessible." },
      { start: 40.50, end: 45.00, text: "allowing people to document everyday life through casual snapshots." },
      { start: 45.00, end: 53.00, text: "Innovations like Color Film and later, Digital photography transformed image making into an instant global activity." },
      { start: 53.00, end: 57.00, text: "It also brought previously less seen parts of the world into public view." },
      { start: 57.00, end: 65.00, text: "In the 1920s, for example, Ansel Adams used photography to capture the vast, unspoiled beauty of the American West." },
      { start: 65.00, end: 70.30, text: "Adams was originally trained as a musician and brought an artist's eye to his compositions." },
      { start: 70.30, end: 74.00, text: "Carefully considering light, form, and balance" },
      { start: 74.00, end: 81.50, text: "His black and white images of national parks emphasize dramatic light, sweeping landscapes, and intricate natural details." },
      { start: 81.50, end: 86.00, text: "These photographs didn't just showcase beauty; they stirred a deep emotional response" },
      { start: 86.20, end: 91.00, text: "and heightened public awareness about the need to protect fragile natural environments." },
      { start: 91.00, end: 98.00, text: "Despite rapid change, photography still relies on core principles: composition, lighting, and perspective." },
      { start: 98.00, end: 101.50, text: "These elements of photography are kind of like grammar and writing." },
      { start: 101.50, end: 107.00, text: "Just like grammar gives language its structure, so do composition, lighting, and perspective." },
      { start: 107.00, end: 112.00, text: "Umm well, they shape how a photograph tells a story and conveys emotions." },
    ],
    vocab: [
      { en: "undergo", ko: "겪다, 경험하다" },
      { en: "remarkable", ko: "놀라운, 주목할 만한" },
      { en: "introduce", ko: "도입하다, 소개하다" },
      { en: "unique", ko: "독특한, 유일한" },
      { en: "reproduce", ko: "복제하다, 재현하다" },
      { en: "prized", ko: "소중히 여겨지는, 귀중한" },
      { en: "clarity", ko: "명료함, 선명함" },
      { en: "accessible", ko: "접근 가능한, 이용하기 쉬운" },
      { en: "document", ko: "기록하다" },
      { en: "transform", ko: "변화시키다, 탈바꿈시키다" },
      { en: "endeavor", ko: "노력, 시도" },
      { en: "vast", ko: "광대한, 드넓은" },
      { en: "unspoiled", ko: "훼손되지 않은, 자연 그대로의" },
      { en: "composition", ko: "구도, 구성" },
      { en: "emphasize", ko: "강조하다" },
      { en: "intricate", ko: "복잡한, 정교한" },
      { en: "stir", ko: "불러일으키다, 자극하다" },
      { en: "perspective", ko: "관점, 원근법" },
      { en: "not only A but also B", ko: "A뿐만 아니라 B도" },
      { en: "as a result of", ko: "~의 결과로" },
      { en: "be prized for", ko: "~로 높이 평가받다" },
      { en: "transform A into B", ko: "A를 B로 바꾸다" },
      { en: "bring A into view", ko: "A를 세상에 알리다" },
      { en: "bring an artist's eye to", ko: "~에 예술가의 시각을 적용하다" },
      { en: "rely on", ko: "~에 의존하다" },
      { en: "stir an emotional response", ko: "감정적 반응을 불러일으키다" },
      { en: "public awareness", ko: "대중의 인식" },
      { en: "Just like A, so do B", ko: "마치 A인 것처럼, B도 그러하다" },
      { en: "be kind of like", ko: "~와 비슷하다" },
      { en: "give structure to", ko: "~에 구조를 부여하다" }
    ]
  }
,
  {
    id: 2,
    title: "Social Capital",
    file: "9_2_1_Social_Capital.m4a",
    sentences: [
      { start: 0.00,  end: 7.50,  text: "Social capital refers to the networks of relationships among people who live and work in a particular society." },
      { start: 7.50,  end: 10.50, text: "Social capital can be bonding or bridging." },
      { start: 10.50, end: 14.40, text: "Bonding social capital occurs within a close-knit group," },
      { start: 14.40, end: 18.40, text: "such as family or close friends, where strong ties exist." },
      { start: 18.40, end: 25.90, text: "Bridging social capital refers to the connections that link people across different social groups," },
      { start: 25.90, end: 29.00, text: "which might involve acquaintances or colleagues." },
      { start: 29.00, end: 35.00, text: "High levels of social capital have been associated with numerous benefits," },
      { start: 35.00, end: 41.30, text: "including improved mental health, higher educational achievement, and greater economic prosperity." },
      { start: 41.30, end: 46.00, text: "It fosters trust, cooperation, and a sense of belonging." },
      { start: 46.00, end: 51.80, text: "However, it's important to note that social capital can also have negative aspects," },
      { start: 51.80, end: 58.00, text: "such as the potential for reinforcing social inequalities due to the exclusion of outsiders." },
      { start: 58.00, end: 63.70, text: "Understanding social capital helps sociologists analyze how communities function." },
      { start: 63.70, end: 67.40, text: "So let's now look at a case study of a specific community." }
    ],
    vocab: [
      { en: "social capital", ko: "사회적 자본" },
      { en: "bonding", ko: "유대, 결속" },
      { en: "bridging", ko: "연결, 가교" },
      { en: "close-knit", ko: "긴밀한, 단단히 결속된" },
      { en: "ties", ko: "유대, 연결고리" },
      { en: "acquaintance", ko: "지인, 아는 사람" },
      { en: "colleague", ko: "동료" },
      { en: "prosperity", ko: "번영, 번창" },
      { en: "foster", ko: "촉진하다, 육성하다" },
      { en: "cooperation", ko: "협력, 협동" },
      { en: "belonging", ko: "소속감" },
      { en: "reinforce", ko: "강화하다" },
      { en: "inequality", ko: "불평등" },
      { en: "exclusion", ko: "배제, 제외" },
      { en: "outsider", ko: "외부인" },
      { en: "sociologist", ko: "사회학자" },
      { en: "analyze", ko: "분석하다" },
      { en: "intentional", ko: "의도적인" },
      { en: "identify", ko: "파악하다, 확인하다" },
      { en: "refer to", ko: "~을 가리키다, 언급하다" },
      { en: "occur within", ko: "~ 안에서 발생하다" },
      { en: "strong ties", ko: "강한 유대" },
      { en: "link people across", ko: "~을 넘어 사람들을 연결하다" },
      { en: "be associated with", ko: "~와 관련되다" },
      { en: "a sense of belonging", ko: "소속감" },
      { en: "it's important to note that", ko: "~을 주목하는 것이 중요하다" },
      { en: "due to", ko: "~ 때문에" },
      { en: "case study", ko: "사례 연구" },
      { en: "seek to", ko: "~하려고 하다" },
      { en: "rather than", ko: "~ 대신에, ~보다는" },
      { en: "result in", ko: "~을 초래하다, ~로 이어지다" },
      { en: "be rejected by", ko: "~에 의해 거부되다" },
      { en: "the established art community", ko: "기성 예술계" },
      { en: "gain recognition", ko: "인정받다" },
      { en: "pave the way for", ko: "~의 길을 열다" },
      { en: "in terms of", ko: "~의 관점에서, ~면에서" },
      { en: "be celebrated for", ko: "~로 칭송받다" }
    ]
  }
    // 새 음원 추가 시 여기에 추가:
  // {
  //   id: 2,
  //   title: "제목",
  //   file: "파일명.m4a",
  //   sentences: [
  //     { start: 0.00, end: 5.00, text: "문장 텍스트" },
  //     ...
  //   ]
  // }
];
